"""Rebuild ``docs/ow_facts/PROGRESS.md`` from current curated/ + raw/ state.

Run after each curation batch so the progress table always reflects truth.

Usage:
    python -m src.regenerate_progress
"""

from __future__ import annotations

import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
RAW_DIR = ROOT / "docs" / "ow_facts" / "raw"
CURATED_DIR = ROOT / "docs" / "ow_facts" / "curated"
OUT = ROOT / "docs" / "ow_facts" / "PROGRESS.md"


def slugify(name: str) -> str:
    """Match SCHEMA.md §entity_slug rules."""
    s = name.lower().replace(" ", "_").replace("'", "")
    return re.sub(r"[^a-z0-9_]", "", s)


def status_for(slug: str) -> str:
    fp = CURATED_DIR / f"{slug}.json"
    if not fp.exists():
        return "⬜ todo"
    cur = json.loads(fp.read_text(encoding="utf-8"))
    if cur.get("source", {}).get("audited_by_human"):
        return "✅ audited"
    return "🟡 draft"


def fact_count(slug: str) -> int:
    fp = CURATED_DIR / f"{slug}.json"
    if not fp.exists():
        return 0
    cur = json.loads(fp.read_text(encoding="utf-8"))
    return sum(len(v) for v in cur.get("facts", {}).values())


def tier_section(tier: str, title: str) -> str:
    tier_dir = RAW_DIR / tier
    if not tier_dir.exists():
        return ""
    files = sorted(tier_dir.glob("*.json"), key=lambda f: f.stem.lower())

    counts = {"audited": 0, "draft": 0, "todo": 0}
    rows = []
    for i, fp in enumerate(files, 1):
        rec = json.loads(fp.read_text(encoding="utf-8"))
        page = rec.get("page", fp.stem)
        slug = slugify(page)
        raw_kb = len(rec.get("wikitext", "")) / 1024
        st = status_for(slug)
        if "audited" in st:
            counts["audited"] += 1
        elif "draft" in st:
            counts["draft"] += 1
        else:
            counts["todo"] += 1
        fc = fact_count(slug)
        fc_cell = f"{fc}" if fc else "—"
        rows.append(f"| {i} | {st} | {page} | `{slug}` | {raw_kb:.1f} KB | {fc_cell} |")

    total = len(files)
    progress_pct = (counts["audited"] / total * 100) if total else 0
    header = (
        f"## {title} ({total} pages — "
        f"{counts['audited']} audited · {counts['draft']} draft · {counts['todo']} todo "
        f"— {progress_pct:.0f}% done)\n"
    )
    table = (
        "| # | Status | Page | Slug | Raw size | Facts |\n"
        "|---|---|---|---|---:|---:|\n"
        + "\n".join(rows)
    )
    return header + "\n" + table + "\n"


def main() -> None:
    parts = [
        "# OW-Socrates SSOT Curation Progress\n",
        "Auto-generated by `src/regenerate_progress.py`. Re-run after each batch.\n",
        "**Legend:**\n",
        "- ✅ audited — `audited_by_human: true`, locked-in fact card",
        "- 🟡 draft   — curated file exists, awaiting human audit",
        "- ⬜ todo    — not yet curated\n",
    ]
    for tier, title in [("p0", "P0 — Essential"), ("p1", "P1 — Supplementary"), ("p2", "P2 — DLC outline")]:
        section = tier_section(tier, title)
        if section:
            parts.append(section)

    OUT.write_text("\n".join(parts), encoding="utf-8")
    print(f"✅ Regenerated {OUT}")


if __name__ == "__main__":
    main()
